# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 17:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='joining',
        ),
        migrations.AddField(
            model_name='trip',
            name='joining',
            field=models.ManyToManyField(null=True, related_name='users_joining', to='users.User'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='planned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
    ]
