# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_auto_20161021_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='joining',
            field=models.ManyToManyField(related_name='users_joining', to='users.User'),
        ),
    ]
